version: 1.0.{build}
image:
- Visual Studio 2017
- Visual Studio 2013
clone_folder: c:\projects\cntlm
build_script:
- cmd: >-
    C:\cygwin\setup-x86.exe -qgnNdO -l C:\cygwin\var\cache\setup -R c:\cygwin -s http://cygwin.mirror.constant.com -P ghostscript -P dos2unix -P zip

    C:\cygwin\bin\bash -e -l -c "cd /cygdrive/c/projects/cntlm && make distclean && ./configure && make DEBUG=1 && make win"

    C:\cygwin\bin\bash -e -l -c "cd /cygdrive/c/projects/cntlm && make distclean && ./configure && make && make win"
artifacts:
- path: cntlm-*.exe
- path: cntlm*.zip
